# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SYvdb6iG6moRVAczORlyYTvaMm1JrIe
"""

def check_bits(A, indices):
  results=[]
  for k in indices:
    mask = 1 << k
    result = A & mask
    if result != 0:
      results.append(yes)
    else:
      results.append(no)
  return results
a=input()
b=input()
c=b+a
x=int(c,2)
n = int(input())
d= [int((input()) for i in range(n))]
print(check_bits(x, list(d)))