# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FsfaB9BRFpSMdwrrypU9BwehhPfPuGvQ
"""

a=int(input())
b=int(input())
x=bin(a).count("1")
y=bin(b).count("1")
if a==b:
  print(0)
else :
  n=a^b
  f=bin(n).count("1")
  print(f)