# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eo-iiqXuj3UVzNlU6ql1uKhRNR7dRGLK
"""



a=int(input())
b=int(input())
x=bin(a).count("1")
y=bin(b).count("1")
if x==y:
  print(0)
else :
  print(x^y)