# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7o91Z5XrXiF_RoSu8FsCjDwOMfbqIno
"""

def sum(*n):
  total = 0
  for num in n:
    total += num
  return total

def average(*n):
  sum = 0
  count = 0
  for num in n:
    sum += num
    count += 1
  if count != 0:
      return round(sum / count,2)
  else:
      return None

def lcd(*n):
  import numpy as np
  lcm = n [0]
  for num in n [1:]:
    lcm = np.lcm (lcm, num)
  return lcm
def gcd(*n):
  import math
  gcd = n [0]
  for num in n [1:]:
    gcd = math.gcd(gcd,num)
  return gcd
def maxx(*lst1):
  return max(lst1)
def minn(*lst1):
  return min(lst1)

func_dict={'sum': sum, 'average': average, 'lcd': lcd,'min':minn,"max":maxx,"gcd":gcd }
operation = input ()
inputs = []
while True:
  user_input = input()
  if user_input == "end":
      break
  inputs.append(int(user_input))

if operation in func_dict:
  result = func_dict [operation] (*inputs)
  print(result)
else:
  print("Invalid command")