# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xn_0UEoGEdcOo1JF9Y7OIOFEUEPh9ErO
"""

def x(f):
    return f+1

a,b=map(int, input().split())

number=0
if a<b:

  for num in range(a,b + 1):

      if num > 1:
          for i in range(2, num):
              if (num % i) == 0:
                  break

          else:
            number=x(number)
  print(f"main order - amount: {number}")
else:
    for num in range(b,a + 1):

      if num > 1:
          for i in range(2, num):
              if (num % i) == 0:
                  break

          else:
            number=x(number)

    print(f"reverse order - amount: {number}")