# -*- coding: utf-8 -*-
"""Fararejery.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HI9uEghul_Zc2utocgi_m0CuAHuJItqD
"""

i, j = 0, 0
n = int(input())
map1 = [['.' for _ in range(n)] for _ in range(1000)]
map1[j][i] = '*'
commands = {"L": (-1, 0), "R": (1, 0), "B": (0, 1)}
while True:
    print('\n'.join(' '.join(row) for row in map1 if any(cell != '.' for cell in row)))
    command = input("Enter the direction (L, R, B, or END): ")
    if command == "END":
        break
    if command not in commands:
        continue
    di, dj = commands[command]
    i = min(max(i + di, 0), n - 1)
    j += dj
    map1[j][i] = '*'
if i != n - 1:
    print("There's no way out!")