# -*- coding: utf-8 -*-
"""hello-world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QPMw52_XVUsNOJ8S0_eOTr70yHkkQaeL
"""

print('hello world' )