# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbHc0D1LttYrK1Ez9MaY4zklN5xQaqO8
"""

def main():
    items = input().split(' ')
    sorted_items = sorted(items, key=lambda x: int(x[1:]))
    print(''.join([i[0] for i in sorted_items]))

main()