# -*- coding: utf-8 -*-
"""konferans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbHc0D1LttYrK1Ez9MaY4zklN5xQaqO8
"""

n = int(input())
domains = sorted({email.split('@', 1)[1] for _ in range(n) if "@" in (email := input())})
for domain in domains:
    try:
        print(domain)
    except IndexError:
        continue