# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQFhtNWKehu2GblzToS9vVdOtYzaRSzm
"""

a=input()
b=input()
c=b+a

n = int(input())
inputs = [int(input()) for i in range(n)]

def get_bit (byteval, idx):
  return ( (byteval & (1 << idx)) != 0)
s = c
x = int (s, 2)
bits_to_check = inputs
for bit in bits_to_check:
  if get_bit (x, bit):
    print (f"yes")
  else:
    print (f"no")