# -*- coding: utf-8 -*-
"""Fararejery2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gn0Bjw-8fBzfVB6X5JZiumaPsYtMW6nL
"""

import numpy as np

cols = input()
try:
    cols = int(cols)
    if cols <= 0:
        raise ValueError
except ValueError:
    exit()

matrix = np.full((5, cols), ".")

row = 0
col = 0

matrix[row][col] = "*"

steps = 0

while True:
    if row == len(matrix) - 1 and col == len(matrix[0]) - 1:

        pass

    direction = input()

    if direction not in ["R", "L", "B", "END"]:
        continue

    if direction == "R":
        col += 1
    elif direction == "L":
        col -= 1
    elif direction == "B":
        row += 1
    elif direction == "END":

        break


    if row < 0 or row >= len(matrix) or col < 0 or col >= len(matrix[0]):

        if direction == "R":
            col -= 1
        elif direction == "L":
            col += 1
        elif direction == "B":
            row -= 1

        continue


    matrix[row][col] = "*"


    steps += 1

if '*' not in matrix[:, -1]:
    print("There's no way out!")

for r in matrix:
    if '*' in r:
        print(' '.join(r))