# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkJHRkOw9qSpwS2u3urBGLaJLOVm_8JD
"""

n = int(input())
def solve(n):
   for i in range(n+1):
      for j in range(n-i):
         print( end='')

      C = 1
      for j in range(1, i+1):
         print(C, ' ', sep='', end='')
         C = C * (i - j) // j
      print()


solve(n)