# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14S_HyKRntAN9iB75sTt4YIAILJlv6YPY
"""

n = int(input())
domains = sorted({input().split('@', 1)[1] for _ in range(n) if "@" in input()})
for domain in domains:
    print(domain)