# -*- coding: utf-8 -*-
"""patv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbHc0D1LttYrK1Ez9MaY4zklN5xQaqO8
"""

import re

a = input()
a = re.sub(r' +', ' ', a.strip())
a = re.sub(r"\\n", "\n", a)

a = list(a)

finresult = []
tmp = 0

for i in a:
    if i == '@':
        finresult.append('@')
        tmp += 1
    elif i == '#' and tmp > 0:
        tmp -= 1
    else:
        finresult.append(i)

print('Formatted Text: ' + ''.join(finresult))